### PR TITLE
Disable inline logs

### PR DESCRIPTION
**Pull request by tdroxler**
resolves https://github.com/alephium/explorer-backend/issues/324

is it enough for you @simerplaha ?

### CODE REVIEW

**Comment by tdroxler** [comment]
@simerplaha `unidoc` is failing in [this line](https://github.com/alephium/explorer-backend/blob/cbe07e5f533ea805fa22715dce64fcbbe713b11b/build.sbt#L95)  what's its purpose?

**Comment by simerplaha** [comment]
The `"_"` means to print all. Documentation [here](https://docs.scala-lang.org/overviews/compiler-options/index.html). 

> -Yopt-log-inline PACKAGE/CLASS.METHOD
Print a summary of inliner activity; _ to print all, prefix match to select.

**Comment by tdroxler** [comment]
> The `"_"` means to print all. Documentation [here](https://docs.scala-lang.org/overviews/compiler-options/index.html).
> 
> > -Yopt-log-inline PACKAGE/CLASS.METHOD
> > Print a summary of inliner activity; _ to print all, prefix match to select.

ok so we can comment that line too, thxxx

**Review by simerplaha — APPROVED** [review]
🚀

**Pull request merged**
