### PR TITLE
Improve post addresses transactions

### PR DESCRIPTION
**Pull request by tdroxler**
`POST /addresses/transactions` was returning duplicate tx if multiple addresses of to the body share some common tx.

We also added `fromTs` and `toTs` optional query params to that endpoint to ease the pagination work.

### CODE REVIEW

**Review by h0ngcha0 — APPROVED** [review]
LGTM :+1:

**Comment by polarker** [comment]
Why this method is `POST` instead of `GET`?

**Comment by tdroxler** [comment]
> Why this method is `POST` instead of `GET`?

You can query transactions for multiple addresses, you pass them in the POST body. As we paginate we don't return more transactionos, limit is the same as the `GET` for one address.

**Comment by polarker** [comment]
> > Why this method is `POST` instead of `GET`?
> 
> You can query transactions for multiple addresses, you pass them in the POST body. As we paginate we don't return more transactionos, limit is the same as the `GET` for one address.

POST is usually used to create a resource
```
POST is used to send data to a server to create/update a resource.
```

**Comment by tdroxler** [comment]
> POST is usually used to create a resource
> 
> ```
> POST is used to send data to a server to create/update a resource.
> ```
yes, but REST doesn't have a nice way to request multiple items, so it's quite common to use POST for that kind of situation. The other solution is to go with chain of query param: `?address=<addr1>&address=<addr2>`, but you have a risk to reach the url length limit, especially with addresses that can be long.

**Comment by polarker** [comment]
I keep forgetting that `GET` does not allow data to be sent to the server. We don't have other choices then.

**Review by polarker — APPROVED** [review]

**Pull request merged**
