### PR TITLE
Rename `unconfirmed-transaction` to `mempool-transaction`/

### PR DESCRIPTION
**Pull request by tdroxler**

### CODE REVIEW

**Comment by polarker** [comment]
I am not sure about `ConfirmedTransaction`, because it's not confirmation if a transaction is included into a new block. It usually takes hours to confirm at the current stage.

How about using `Transaction` + `MempoolTransaction` instead of `ConfirmedTransaction`? Since the trait is `TransactionLike`, this naming should work?

**Review by simerplaha — APPROVED** [review]
🚀

**Comment by tdroxler** [comment]
> I am not sure about `ConfirmedTransaction`, because it's not confirmation if a transaction is included into a new block. It usually takes hours to confirm at the current stage.
> 
> How about using `Transaction` + `MempoolTransaction` instead of `ConfirmedTransaction`? Since the trait is `TransactionLike`, this naming should work?

We already have `Transaction`, we duplicated `ConfirmedTransaction` otherwise tapir was creating a `Transaction1` schema depending if it was used as a `Transaction` or in the `TransactionLike` context. This was also raised in [that issue](https://github.com/alephium/explorer-backend/issues/427). I'll spend a bit of time on this, I'm pretty sure we can tweak the openapi generation.

**Comment by tdroxler** [comment]
@polarker I pushed the changes we discussed:

* Transaction
* MempoolTransaction
* TransactionLike = AccpetedTransaction | PendingTransaction

**Review by polarker — APPROVED** [review]
LGTM. Does it well with Typescript now?

**Pull request merged**
